Express
MonserratGenereux/Moviles-Backend pull request #7
Opened 2017-02-23 17:42 UTC by MonserratGenereux

Closes #3
Closes #4 
Closes #5
Closes #6

2017-02-23 17:47 UTC, dtoledom requested changes

2017-02-23 17:47 UTC, dtoledo23 commented on app/models/responsable.js
> +    MemberSince: String,
Change it to `memberSince`

2017-02-23 17:47 UTC, dtoledo23 commented on app/models/stores.js
> +    responsable: String
This field is repeated. Erase one.

2017-02-23 17:47 UTC, dtoledo23 commented on router.js
> +let router = require('express').Router();
Use two spaces instead of tab characters in the entire file. You can configure your text editor to do that.

2017-02-23 17:47 UTC, dtoledo23 commented on router.js
> +	console.log(req.body);
Delete this console logs.

2017-02-23 17:47 UTC, dtoledo23 commented on server.js
> +//Schemas
These schemas are not used anywhere. Don't import stuff you are not using.

2017-02-23 17:47 UTC, dtoledo23 commented on server.js
> +mongoose.connect("mongodb://localhost:27017/ProyectoMoviles", function(err,db){
Add an issue to handle this hardcoded connection url in a better way.

2017-02-23 17:47 UTC, dtoledo23 commented on server.js
> +	res.send('hola mundo');
Use another message for the Get request to the root. Somethin like `Moviles API`

2017-02-23 17:47 UTC, dtoledo23 commented on server.js
> +})
Add new line.

2017-02-27 00:53 UTC, MonserratGenereux commented on server.js
> +})
listo 💃

2017-02-27 00:53 UTC, MonserratGenereux commented on router.js
> +let router = require('express').Router();
Ya 😃

2017-02-27 04:41 UTC, dtoledom approved these changes
LGTM

2017-02-28 06:16 UTC, merged